name: Build Ghost APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Updated to v4

      - name: Build with Buildozer
        # Naya working action link
        uses: Georgiev_K/buildozer-action@v1
        with:
          buildozer_version: master
          command: buildozer android debug
          
      - name: Upload APK Artifact
        # Error fix: Updated from v2 to v4
        uses: actions/upload-artifact@v4
        with:
          name: full-ghost-v6-apk
          path: bin/*.apk
