name: Build V4 WebView APK
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev libxml2-dev libxslt1-dev gettext m4 python3-pip python3-setuptools libsqlite3-dev sqlite3
          python3 -m pip install --user --upgrade buildozer Cython==0.29.33
      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          buildozer -v android debug

