name: Build Ghost APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Buildozer
        uses: ArtemShatem/buildozer-action@v1.2
        with:
          buildozer_version: master
          command: buildozer android debug
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ghost-v6-apk
          path: bin/*.apk
